name: Production Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Deno
      run: |
        curl -fsSL https://deno.land/x/install/install.sh | sh -s v1.15.1
        $HOME/.deno/bin/deno run -A https://deno.land/x/aleph@v0.3.0-beta.19/install.ts
    - name: Build
      run: |
        export PATH=$HOME/.deno/bin:$PATH
        aleph build .
    - name: Deploy
      run: |
        aws s3 --region "$AWS_DEFAULT_REGION" sync ./dist s3://soma.brimworks.com
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
